import { ConnectButton } from "@rainbow-me/rainbowkit";
import { type NextPage } from "next";
import Head from "next/head";

import { useNewOpProposal } from "~/hooks/write";
import { BN } from "~/hooks/op-helpers";
import {
  useCanCreateOpProposal,
  useOpSettings,
  useOpProposal,
} from "~/hooks/read";

const Home: NextPage = () => {
  const { isMember } = useCanCreateOpProposal(
    "0x47d80912400ef8f8224531EBEB1ce8f2ACf4b75a"
  );

  const { settings } = useOpSettings();
  const { proposal } = useOpProposal(1);
  const { write, error, status } = useNewOpProposal({
    metadata: "0x00",
    actions: [
      {
        data: "0x00",
        to: "0x47d80912400ef8f8224531EBEB1ce8f2ACf4b75a",
        value: BN(420),
      },
    ],
    allowFailureMap: BN(0),
  });

  const handleClick = () => {
    console.log("<====> BEING CALLED <====>");
    write?.();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="hero min-h-screen bg-base-200">
        <div className="mockup-code">
          <button onClick={() => handleClick()} className="btn-primary btn">
            OpTx
          </button>
          <pre data-prefix="$">
            <code>npm i daisyui</code>
          </pre>
          {isMember && (
            <pre data-prefix="$">
              <code>isMember {String(isMember)}</code>
            </pre>
          )}
          {/* <TerminalLine text={permission} /> */}
          {/* <TerminalLine text={isMember?.toString()} /> */}
        </div>
      </div>
      {settings && <pre>{JSON.stringify(settings, null, 2)}</pre>}
      {proposal && <pre>{JSON.stringify(proposal, null, 2)}</pre>}
    </>
  );
};

export default Home;

const TerminalLine = (text: any | undefined) => {
  return <pre data-prefix="$">{text && <code>{text}</code>}</pre>;
};

const Navbar = () => {
  return (
    <div className="navbar justify-between bg-base-100 px-4">
      <a className="btn-ghost btn text-xl normal-case">daisyUI</a>
      <ConnectButton />
    </div>
  );
};
